name: solfacil_firebase_sdk
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_crashlytics: ^3.0.11
  firebase_messaging: ^14.2.1
  firebase_in_app_messaging: ^0.7.0+10
  solfacil_tools_sdk:
    git:
      url: https://github.com/solfacil/sdk-tools-mobile
      ref: feature/SPR-729-remove-firebase-from-sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
