name: solfacil_firebase_sdk
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.20.0
  firebase_analytics: ^9.2.1
  firebase_crashlytics: ^2.8.6
  cloud_firestore: ^3.4.0
  solfacil_tools_sdk:
    git:
      url: https://github.com/solfacil/sdk-tools-mobile
      ref: feature/SPR-729-remove-firebase-from-sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
